# Ref: https://github.com/marketplace/actions/copy-to-branches-action
name: Copy To Branches
'on':
  workflow_dispatch: null
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: actions/copy-to-branches@v1.2
        env:
          key: main
